<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers>osx-arm64;osx-x64</RuntimeIdentifiers>
    <AssemblyName>CodexUsage</AssemblyName>
    <RootNamespace>CodexUsage.macOS</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../CodexUsage.Codex/CodexUsage.Codex.csproj" />
    <ProjectReference Include="../CodexUsage.Desktop/CodexUsage.Desktop.csproj" />
  </ItemGroup>
</Project>
